### ISSUE TITLE
Using stylelint-config-recommended v12, stylelint gives syntax error

### ISSUE THREAD

**Issue by kenbankspeng** [stylelint/stylelint-config-recommended#188]
### What steps are needed to reproduce the bug?

1) Upgrade stylelint-config-recommended from v11.0.0 to v12.0.0. (declaration-block-no-duplicate-properties option from ignore: ['consecutive-duplicates-with-different-values'] to ignore: ['consecutive-duplicates-with-different-syntaxes'])
     
2) Run stylelint against a code base containing duplicate css entries

For example, I'm using css-in-js, setting a clip-path to a default, then conditionally setting it to another value.

```
const ClipPath = styled.div`
  clip-path: polygon(0 0, 100% 100%, 100% 0, 0 0);
  clip-path: ${(p) => p.$up && 'polygon(100% 0, 0 100%, 0 0, 100% 0)'};
`;
```

### What did you expect to happen?

I expected stylelint to either tell me my codebase is fine or tell me where my codebase fails to meet the new v12 recommended rules.

### What actually happened?

 SyntaxError: Unexpected input
    at TokenStream.error (/Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/css-tree@2.3.1/node_modules/css-tree/cjs/parser/create.cjs:270:19)
    at parse (/Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/css-tree@2.3.1/node_modules/css-tree/cjs/parser/create.cjs:324:20)
    at isEqualValueSyntaxes (/Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/stylelint@15.5.0/node_modules/stylelint/lib/rules/declaration-block-no-duplicate-properties/index.js:79:21)
    at /Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/stylelint@15.5.0/node_modules/stylelint/lib/rules/declaration-block-no-duplicate-properties/index.js:207:46
    at Array.forEach (<anonymous>)
    at /Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/stylelint@15.5.0/node_modules/stylelint/lib/rules/declaration-block-no-duplicate-properties/index.js:134:4
    at each (/Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/stylelint@15.5.0/node_modules/stylelint/lib/utils/eachDeclarationBlock.js:55:5)
    at eachDeclarationBlock (/Users/ken/Documents/Software/pulltask-dev/node_modules/.pnpm/stylelint@15.5.0/node_modules/stylelint/lib/utils/eachDeclarationBlock.js:60:2)

**Comment by wadehammes** [comment]
Also getting the same error and the error message is not very helpful

**Comment by wadehammes** [comment]
Workaround:

Add to your `.stylelintrc`
```
"declaration-block-no-duplicate-properties": [
      true,
      {
        "ignore": []
      }
    ]
```
run your linting. This will give you some errors, which in my case were valid, duplicated properties in some of my styled-components.

I fixed those, added back `consecutive-duplicates-with-different-syntaxes` to the ignore array and it passed testing.

**Comment by ybiquitous** [comment]
@kenbankspeng @wadehammes Thanks for the report and the help! We're tracking the same problem on <https://github.com/stylelint/stylelint/issues/6791>, and we will release a fixed version in a few days.
